### ISSUE TITLE
ufifo使用疑问咨询

### ISSUE THREAD

**Issue by fancong5201314** [ShenChen1/ufifo#1]
大佬，在看Freak的时候，看到ufifo里面关于media的设置，针对video_stream，里面用到了share模式，一对多，在验证的时候，我发现以下疑问，望大佬解答一下，谢谢：

生产者一直跑，一直抛流，ufifo的4MB空间会满，会阻塞，这句话只会丢弃一帧数据，还是会阻塞：
`if (fifo->len(fifo) + total_size > fifo->size(fifo)) { fifo->skip(fifo); fifo->oldest(fifo); }`
我改成如下方式就不会阻塞了：
`while (fifo->len(fifo) + total_size > fifo->size(fifo)) { fifo->skip(fifo); fifo->oldest(fifo); }`
以上问题，想请教一下大佬。
打扰了，非常感谢

**Comment by ShenChen1** [comment]
第一个应该是先跳过一帧，然后再跳到最前面的I帧，保证有空间收数据
第二个是不是因为你改了第一个，然后可能consumer跟producer速度不匹配导致的？

**Comment by fancong5201314** [comment]
谢谢大佬抽时间回复，第一个跳过一帧，再跳到最前面的一帧，如果空间不够，理论上应该再跳，直至空间足够，这样理解可以吗？第二个我才用了阻塞的方式获取，每次都可以获取，但是问题在于get的间隔没法控制，并不是生产者每产生一帧，消费者就能及时获取，消费者这边可能会阻塞一下，然后一次性拿到了多个

**Comment by fancong5201314** [comment]
如果这个地方不修改，还是采用if进行判断，则生产者在4M的buffer满了之后，会阻塞

**Comment by fancong5201314** [comment]
在获取的时候，如果我采用超时1000毫秒，好像并未起效，生产者那边停止，还是可以正常获取数据，不过每次都是最后一帧
![image](https://github.com/user-attachments/assets/7813184c-00e9-4cff-8d76-5e4926cde76b)
![image](https://github.com/user-attachments/assets/5494b63c-3436-49d3-a906-e6e887dce9cb)

**Comment by fancong5201314** [comment]
大佬，这是我的测试代码：
生产者：
`
int main(int argc, const char *argv[])
{
    if (argc != 3)
    {
        ERROR("Usage: %s <share_str> <src.prv>\n", argv[0]);
        return -1;
    }

    int nRet = 0;
    int nFrameType = 0;
    int dwFrameHeadLength = 0;
    int nFrameDataLength = 0;
    char* pFrameData = NULL;
    char* pFrameHeadAddress = NULL;
    H264DATAPACKETHEADER *pRawHead = NULL;
    MPEG4FILEHEADER PrvFileHead = {0};

    mfifo_t *fifo = mfifo_create(argv[1], 4 * 1024 * 1024);
    assert(fifo);

    nRet = OpenRawFile(argv[2], &PrvFileHead);
    if (nRet)
    {
        ERROR("Fail to called OpenRawFile!\n");
        fifo->destroy(fifo);
        return -1;
    }

    if (FILE_START_CODE == PrvFileHead.FileStartCode)
    {
        DEBUG("Warning: prv file %s not has file head.\n", argv[2]);
    }

    while (1)
    {
        usleep(33*1000);
        nRet = ReadFrameData(&pFrameHeadAddress, &dwFrameHeadLength, &nFrameType, &pFrameData, &nFrameDataLength);
        if (0 == nRet)
        {
            pRawHead = (H264DATAPACKETHEADER *)pFrameHeadAddress;
            if (FRAME_START_CODE == pRawHead->DataPacketStartCode)
            {
                if (pRawHead->FrameType == 0x8)
                {
                    continue;
                }

                DEBUG("no: %-5d, crc: %#x, type: %#x, lt: %#x, showtime: %u, real_sec: %lu, real_usec: %lu, frame_size: %u\n", 
                      pRawHead->FrameNo, pRawHead->DataPacketStartCode, pRawHead->FrameType,
                      pRawHead->byLoadType, pRawHead->ShowTime, pRawHead->u32RealTimeSec,
                      pRawHead->u32RealTimeUSec, pRawHead->nOverloadLen);

                size_t total_size = sizeof(media_record_t) + nFrameDataLength;

                //while (fifo->len(fifo) + total_size > fifo->size(fifo))
                if (fifo->len(fifo) + total_size > fifo->size(fifo))
                {
                    fifo->skip(fifo);
                    fifo->oldest(fifo);
                }

                int ret = fifo->put(fifo, pFrameData, total_size, -1);
                //INFO("ret = %d, total_size = %u\n", ret, total_size);
            }
        }
        else
        {
            CloseRawFile();
            //OpenRawFile(argv[2], &PrvFileHead);
            break;
        }
    }

    fifo->destroy(fifo);;

    return 0;
}
`
消费者：
`
    FILE *dst_fp = NULL;
    dst_fp = fopen(argv[2], "wb");
    if (!dst_fp)
    {
        ERROR("Fail to fopen %s.\n", argv[2]);
        return -1;
    }

	uint32_t length = 512*1024;
	uint8_t* data = NULL;
    data = calloc(1, length);
    assert(data);
    media_record_t *rec = (media_record_t *)data;

    mfifo_t *fifo = mfifo_attach(argv[1], 1);
    assert(fifo);
    fifo->newest(fifo); // frame

    while (1)
    {
        fifo->get(fifo, data, length, 1000);
        if (rec->size > 0)
        {
            H264DATAPACKETHEADER *pRawHead = NULL;
            pRawHead = (H264DATAPACKETHEADER *)rec->buf;
            INFO("no: %-5d, crc: %#x, type: %#x, lt: %#x, showtime: %u, real_sec: %lu, real_usec: %lu, frame_size: %u\n", 
                  pRawHead->FrameNo, pRawHead->DataPacketStartCode, pRawHead->FrameType,
                  pRawHead->byLoadType, pRawHead->ShowTime, pRawHead->u32RealTimeSec,
                  pRawHead->u32RealTimeUSec, pRawHead->nOverloadLen);

            fwrite((char*)pRawHead+sizeof(H264DATAPACKETHEADER), pRawHead->nOverloadLen, 1, dst_fp);
            fflush(dst_fp);
        }
        else
        {
            ERROR("rec->size = %d\n", rec->size);
        }
        usleep(33*1000);
    }

    fifo->destroy(fifo);
    fclose(dst_fp);

    return 0;
}
`
辛苦大佬帮我瞅瞅，谢谢

**Comment by ShenChen1** [comment]
> 如果空间不够，理论上应该再跳，直至空间足够，这样理解可以吗？

可以的，难道你的I帧爆大？

> 但是问题在于get的间隔没法控制，并不是生产者每产生一帧，消费者就能及时获取，

这个地方用阻塞的话可以去掉usleep
不能及时get感觉跟底下的semaphore有关系

**Comment by ShenChen1** [comment]
一对多情况下，semaphore好像有点问题，你要不判断一下如果是share模式，那么在内部ufifo_get的地方再put一个semaphore试试

**Comment by fancong5201314** [comment]
> > 如果空间不够，理论上应该再跳，直至空间足够，这样理解可以吗？
> 
> 可以的，难道你的I帧爆大？
> 
> > 但是问题在于get的间隔没法控制，并不是生产者每产生一帧，消费者就能及时获取，
> 
> 这个地方用阻塞的话可以去掉usleep 不能及时get感觉跟底下的semaphore有关系

1. 个人认为理论上应该用while循环进行判断，避免阻塞；
2. 一对多的我看看信号量这边，大佬，您这边没用过一对多的吗？我看代码里面的rtsp和web实时流这边也是一对二的情况；

**Comment by fancong5201314** [comment]
大佬，搞定了，__ufifo_bsem_timedwait这个接口有问题，sem_timedwait直接返回错误，需要修改

**Comment by ShenChen1** [comment]
> sem_timedwait直接返回错误

所以返回了什么errno?

**Comment by fancong5201314** [comment]
> > sem_timedwait直接返回错误
> 
> 所以返回了什么errno?

sem_timedwait直接返回-1，超时： sem_timedwait ret = -1: Connection timed out， 没有任何等待

**Comment by ShenChen1** [comment]
> sem_timedwait直接返回-1，超时： sem_timedwait ret = -1: Connection timed out， 没有任何等待

是因为producer里面发完直接调用了destroy了，导致semaphore被销毁了，然后consumer里面get的时候semaphore操作直接返回失败，但是由于没有判断ret，所以还在使用之前的内存？

**Comment by fancong5201314** [comment]
> > sem_timedwait直接返回-1，超时： sem_timedwait ret = -1: Connection timed out， 没有任何等待
> 
> 是因为producer里面发完直接调用了destroy了，导致semaphore被销毁了，然后consumer里面get的时候semaphore操作直接返回失败，但是由于没有判断ret，所以还在使用之前的内存？

应该不是，是sem_timedwait的问题，我改成如下就可以了：
`
static int __ufifo_bsem_timedwait(sem_t *bsem, lock_t *lock, long millisec)
{
    int ret = 0;
    long secs = 0, add = 0;
    struct timespec wt = {0};

    __ufifo_lock_release(lock);
    clock_gettime(CLOCK_REALTIME, &wt);

	secs = millisec / 1000;
	millisec = millisec % 1000;
	millisec = millisec * 1000 * 1000 + wt.tv_nsec;
	add = millisec / (1000 * 1000 * 1000);
	wt.tv_sec += (add + secs);
	wt.tv_nsec = millisec % (1000 * 1000 * 1000);

    ret = sem_timedwait(bsem, &wt);
    if (ret && errno == ETIMEDOUT)
    {
        ret = ETIMEDOUT;
    }
    __ufifo_lock_acquire(lock);

    return ret;
}

`

**Comment by fancong5201314** [comment]
> > sem_timedwait直接返回-1，超时： sem_timedwait ret = -1: Connection timed out， 没有任何等待
> 
> 是因为producer里面发完直接调用了destroy了，导致semaphore被销毁了，然后consumer里面get的时候semaphore操作直接返回失败，但是由于没有判断ret，所以还在使用之前的内存？

如果semaphore被销毁，会造成段错误吧

**Comment by fancong5201314** [comment]
感觉一对多还是有问题，随着我的消费者增多，custom的获取卡顿会越来越明显，但是不丢帧，例如，2个消费者，则会每两帧卡顿一下，一次来两帧；如果3个消费者，则会每3帧卡顿一下，一次来3帧，依次类推

**Comment by ShenChen1** [comment]
> 一对多情况下，semaphore好像有点问题，你要不判断一下如果是share模式，那么在内部ufifo_get的地方再put一个semaphore试试

这个试下？

**Comment by fancong5201314** [comment]
> > 一对多情况下，semaphore好像有点问题，你要不判断一下如果是share模式，那么在内部ufifo_get的地方再put一个semaphore试试
> 
> 这个试下？

post一个rsem吗？
这个里面有post啊
![image](https://github.com/user-attachments/assets/26fdc47c-f81e-499b-9197-9bd96e243fe5)

**Comment by ShenChen1** [comment]
这里这个是write的，因为被读走了可能有空间让阻塞的生产者再检查一下

需要加的是个read的，要在share模式下

这个处理得欠考虑，后面打算换成条件变量，这样就能用广播触发全部阻塞的了

**Comment by fancong5201314** [comment]
> 这里这个是write的，因为被读走了可能有空间让阻塞的生产者再检查一下
> 
> 需要加的是个read的，要在share模式下
> 
> 这个处理得欠考虑，后面打算换成条件变量，这样就能用广播触发全部阻塞的了

大佬啥时候有时间优化一下呗

**Comment by fancong5201314** [comment]
> 这里这个是write的，因为被读走了可能有空间让阻塞的生产者再检查一下
> 
> 需要加的是个read的，要在share模式下
> 
> 这个处理得欠考虑，后面打算换成条件变量，这样就能用广播触发全部阻塞的了

![image](https://github.com/user-attachments/assets/15839cb4-af93-42e6-ac56-b419145a542a)
这样加可以吗?

**Comment by ShenChen1** [comment]
> 大佬啥时候有时间优化一下呗

随缘吧😵现在是没有时间搞了

> 这样加可以吗?

对的，这是一个WA😪，能达到你的预期么

**Comment by fancong5201314** [comment]
> > 大佬啥时候有时间优化一下呗
> 
> 随缘吧😵现在是没有时间搞了
> 
> > 这样加可以吗?
> 
> 对的，这是一个WA😪，能达到你的预期么

我试试看，谢谢大佬指点

**Comment by fancong5201314** [comment]
> > 大佬啥时候有时间优化一下呗
> 
> 随缘吧😵现在是没有时间搞了
> 
> > 这样加可以吗?
> 
> 对的，这是一个WA😪，能达到你的预期么

加上之后，可以解决卡顿的情况，但是获取重复的情况还是会出现，特别是生产者比较慢(33ms一次)的情况
![image](https://github.com/user-attachments/assets/478713a1-bb5a-4f49-bee6-b69c2a2c88dd)
如果生产者快，则重复的情况会小一些；

**Comment by ShenChen1** [comment]
之前那个get函数的返回值判断了么

现在这么改是为了让其他消费者不卡住，如果新post的semaphore又被当前的消费者消耗了而又没有新的数据上来，那么第二次读不到东西的

按照你之前给的代码片段，如果失败内存是不清的咯，所以数据是一样的？

**Comment by fancong5201314** [comment]
> get

大佬，加上get返回值判断就可以了，谢谢大佬指点，后面换成条件变量，用广播触发全部阻塞，还是依靠大佬了
